version: "3.8"
services:
    db:
    image: postgres:15
    container_name: postgres_container
    volumes:
      - postgresdata:/var/lib/postgresql/data
    env_file:
      - .env:
      
    kyber:
      build: .
      container_name: kyber_container
      env_file:
      - .env:
      depends_on:
        - db
        - redis
      ports:
        - 8080

    
      volumes:
        postgresdata: